import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import Form from '../components/Form/form.jsx';
import Navbar from '../components/Navbar';
import Card from '../components/Form/card';
import Tutorial from '../components/tutorial';
import AppSection from '../components/AppSection';
import Footer from '../components/Footer';

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />
			<main>
				<section className="bg-yellow">
					<div className="container section container--flex">
						<Card />
						<article>
							<Tutorial />
						</article>
					</div>
				</section>

				<section className="bg-grey">
					<div className="container">
						<AppSection />
					</div>
				</section>
			</main>

			<Footer />
		</div>
	);
}
