import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import Form from '../components/Form/form.jsx';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />
			<main>
				<section></section>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
